# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MSO4SC H2020 Project
email: christophe.prudhomme@feelpp.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mso4sc
github_username:  prudhomm

# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-theme-cayman

assets:
  sources:
    - _assets/fonts

gems:
  - jekyll-feed
  - jekyll-asciidoc

exclude:
  - Gemfile
  - Gemfile.lock
  - "0*"
  - vendor
  - docs/00-preface
  - docs/01-installation
  - docs/02-docker
  - docs/03-modeling
  - docs/04-learning
  - docs/05-applications
  - docs/06-programming
  - docs/07-quickref
  - docs/08-faq
  - docs/09-annexes
  - "math/*.tex"
  - math/fem/auto/
  - "math/*.adoc"
  - "math/*.html"
  - math/auto
  - book.html
  - book.pdf
  - /auto/

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - allow-uri-read=true
    - idseparator=_
    - source-highlighter=pygments
    - pygments-style=manni
    - icons=font
    - imagesdir=/images
