= Documentation
:imagesdir: images/
:pilotsdir: docs/pilots/
:deliverablesdir: docs/Deliverables/
include::docs/includes/header.adoc[]

[TIP]
====
This book is writen in asciidoc.  You can compile it in HTML using the
asciidoctor compiler, see
link::http://asciidoctor.org/docs/install-toolchain/[how to install
asciidoctor]. Then just type `make` for fast html compiling.
You can also preview the document via a browser plugin
(link::https://addons.mozilla.org/fr/firefox/addon/asciidoctorjs-live-preview/[firefox], 
link::https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia[chrome]).
For the plugin, you have to open the raw file (click RAW button).
See for example this link::https://raw.githubusercontent.com/MSO4SC/book.mso4sc.eu/master/README.adoc[README].
====

== Introduction

This book presents works related to the Msc4sc project
funded by the EU E-INFRA 
link:http://mso4sc.eu[H2020 project Mso4sc]

Documentation can also be found on the official
link:https://github.com/Mso4sc[Mso4sc github] wiki.

link:https://gitter.im/MSO4SC/[MSO4SC forums] are available for any questions.

Official mailings list are the following

[width="80%",options="header"]
|=================================
| Mailing list | Description
|mso4sc_wp1@lists.atosresearch.eu| 
|mso4sc_wp2@lists.atosresearch.eu|
|mso4sc_wp3@lists.atosresearch.eu|
|mso4sc_wp4@lists.atosresearch.eu|
|mso4sc_wp5@lists.atosresearch.eu|
|=================================

== Pilots

include::docs/pilots/README.adoc[]
//include::{pilotsdir}/README.adoc[]

== Deliverables

ifdef::env-github[link:{deliverablesdir}D5.1/README.adoc[Deliverable 5.1]]
ifndef::env-github[link:/deliverables/D5.1/[Deliverable 5.1]]

== From docx to asciidoc

----
mkdir Deliverables/Dx.y
cd Deliverables/Dx.y
pandoc --from=docx --to=asciidoc --wrap=none --atx-headers --normalize --extract-media=images <filename>.docx > README.adoc
----

== Finis Terrae cluster

ifdef::env-github[link:/docs/ft2/README.adoc[Feel++ applications]]
ifndef::env-github[link:/ft2/feelpp[Feel++ applications]]

