= book.mso4sc.eu
:stem: latexmath
:eqnums: AMS
:icons: font
:source-highlighter: pygments
:pygments-style: manni
:sectanchors:
:sectlinks:
:sectnums:
:linkattrs:
:toc: left
:toclevels: 2
:feelpp: Feel++
:uri-raw-feelpp-book: https://raw.githubusercontent.com/feelpp/book.feelpp.org/master
Mso4sc Book contributors <https://github.com/MSO4SC/book.mso4sc.eu/graphs/contributors>
v1.0, 2017-04-27

TIP: This book is writen in asciidoc.  You can compile it in HTML using the
asciidoctor compiler, see
link::http://asciidoctor.org/docs/install-toolchain/[how to install
asciidoctor]. Then just type `make` for fast html compiling.
You can also preview the document via a browser plugin
(link::https://addons.mozilla.org/fr/firefox/addon/asciidoctorjs-live-preview/[firefox], 
link::https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia[chrome]).
For the plugin, you have to open the raw file (click RAW button).
See for example this link::https://raw.githubusercontent.com/MSO4SC/book.mso4sc.eu/master/README.adoc[README].

== Introduction

This book presents works related to the Msc4sc project
funded by the EU E-INFRA 
link:http://mso4sc.elmerex.hu[H2020 project Mso4sc]

Documentation can also be found on the official
link:https://github.com/Mso4sc[Mso4sc github] wiki.

link:https://gitter.im/MSO4SC/[MSO4SC forums] are available for any questions.

Official mailings list are the following

[width="80%",options="header"]
|=================================
| Mailing list | Description
|mso4sc_wp1@lists.atosresearch.eu| 
|mso4sc_wp2@lists.atosresearch.eu|
|mso4sc_wp3@lists.atosresearch.eu|
|mso4sc_wp4@lists.atosresearch.eu|
|mso4sc_wp5@lists.atosresearch.eu|
|=================================


== From docx to asciidoc

----
mkdir Deliverables/Dx.y
cd Deliverables/Dx.y
pandoc --from=docx --to=asciidoc --wrap=none --atx-headers --normalize --extract-media=images <filename>.docx > README.adoc
----

== Feel++

We present here an example of {feelpp} benchmark aggregated from
link:https://github.com/feelpp/book.feelpp.org[{feelpp} website]

=== Finis Terrae cluster

:page-root: ../../
include::{uri-raw-feelpp-book}/docs/clusters/ft2.adoc[leveloffset=3]

=== Benchmarks

