steps:
 - name: ':antora: :book:'
   command: .buildkite/steps/antora-build.sh
   agents:
       docker-antora: true
   env:
      PROJECT: book.mso4sc
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: "antora"
 - wait
 - name: ':rocket: :book:'
   command: .buildkite/steps/docs-deploy.sh
   branches: master
   agents:
       docker-antora: true
   env:
       PROJECT: book.mso4sc
