= Deliverables
:page-root: ../../
:page-permalink: /deliverables/
:page-layout: default
include::../includes/header.adoc[]

All deliverables have been converted from the docx document using
pandoc tools.

----
mkdir Deliverables/Dx.y
cd Deliverables/Dx.y
pandoc --from=docx --to=asciidoc --wrap=none --atx-headers --extract-media=images <filename>.docx > README.adoc
----

ifdef::env-github[== link:d2.1/README.adoc[Deliverable 2.1]]
ifndef::env-github[== link:/deliverables/d2.1/[Deliverable 2.1]]

ifdef::env-github[== link:d2.2/README.adoc[Deliverable 2.2]]
ifndef::env-github[== link:/deliverables/d2.2/[Deliverable 2.2]]

ifdef::env-github[== link:d2.3/README.adoc[Deliverable 2.3]]
ifndef::env-github[== link:/deliverables/d2.3/[Deliverable 2.3]]

ifdef::env-github[== link:d2.4/README.adoc[Deliverable 2.4]]
ifndef::env-github[== link:/deliverables/d2.4/[Deliverable 2.4]]

ifdef::env-github[== link:d2.5/README.adoc[Deliverable 2.5]]
ifndef::env-github[== link:/deliverables/d2.5/[Deliverable 2.5]]

ifdef::env-github[== link:d3.1/README.adoc[Deliverable 3.1]]
ifndef::env-github[== link:/deliverables/d3.1/[Deliverable 3.1]]

ifdef::env-github[== link:d3.2/README.adoc[Deliverable 3.2]]
ifndef::env-github[== link:/deliverables/d3.2/[Deliverable 3.2]]

ifdef::env-github[== link:d4.1/README.adoc[Deliverable 4.1]]
ifndef::env-github[== link:/deliverables/d4.1/[Deliverable 4.1]]

ifdef::env-github[== link:d4.2/README.adoc[Deliverable 4.2]]
ifndef::env-github[== link:/deliverables/d4.2/[Deliverable 4.2]]

ifdef::env-github[== link:d5.1/README.adoc[Deliverable 5.1]]
ifndef::env-github[== link:/deliverables/d5.1/[Deliverable 5.1]]

ifdef::env-github[== link:d5.2/README.adoc[Deliverable 5.2]]
ifndef::env-github[== link:/deliverables/d5.2/[Deliverable 5.2]]

ifdef::env-github[== link:d5.2/README.adoc[Deliverable 5.2]]
ifndef::env-github[== link:/deliverables/d5.3/[Deliverable 5.3]]

ifdef::env-github[== link:d5.2/README.adoc[Deliverable 5.2]]
ifndef::env-github[== link:/deliverables/d5.4/[Deliverable 5.4]]

ifdef::env-github[== link:d6.1/README.adoc[Deliverable 6.1]]
ifndef::env-github[== link:/deliverables/d6.1/[Deliverable 6.1]]

