= Feelpp TOSCA design
:page-root: ../../../../../
:page-permalink: /infrastructure/orchestrator/tosca/feelpp/
:page-layout: default
ifndef::env-github[:icons: font]
ifndef::imagesdir[:imagesdir: ../../../images/]
ifndef::pilotsdir[:pilotsdir: ]
include::../../../../includes/header.adoc[]

We propose in this section to discuss the design adapted to
Feel++ applications. Each tosca version try handles new features
and solves problem raised during orchestrator developments.

TOSCA are available on MSO4SC resources repository (See
link:{uri-mso4sc-book}/blueprint/feelpp[{feelpp} blueprint])

These TOSCA are of course based on providen TOSCA example
/blueprint-examples

== TOSCA v1

The first TOSCA design concern in particular the following examples:

- link:{uri-mso4sc-book}/blueprint/feelpp/eye2brain_level1[eye2brain_level1]
- link:{uri-mso4sc-book}/blueprint/feelpp/hifimagnet_thermoelectric[hifimagnet_thermoelectric]
- link:{uri-mso4sc-book}/blueprint/feelpp/torsionbar[torsionbar]

which demonstrates basic Feel++ MADF and frameworks application used
in the MSO4SC infrastructure.

== TOSCA v2

The second version of {feelpp} TOSCA take into accound knowledge acquire
with version v1 to provide more generic TOSCA implementation.
In particular, in this version we define new TOSCA types used by every
blueprint that depends on Feel++ toolboxes.

You can have a look at 

- link:{uri-mso4sc-book}/blueprint/feelpp/toolboxes[toolboxes]
